# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Engineering Stephen.
tagline:          'Systematically automate your happiness.'
description:      'Can Computer Science + Economics + Astrophysics + Neuroscience = Happiness? <br> <a href="/pages/signup.html"> Let''s find out together! </a>'
url:              https://stephensebro.com
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Stephen Sebro'
  url:            https://twitter.com/ssebro

paginate:         2
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap

# Custom vars
version:            
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             

disqus:
  shortname:  stephensebro

google_analytics: UA-126655391-1
